//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: address.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Ru_Zveron_Contract_AddressServiceClient`, then call methods of this protocol to make API calls.
public protocol Ru_Zveron_Contract_AddressServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? { get }

  func saveAddressIfNotExists(
    _ request: Ru_Zveron_Contract_AddressRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_Contract_AddressRequest, Ru_Zveron_Contract_AddressResponse>

  func getAddress(
    _ request: Ru_Zveron_Contract_AddressIdRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_Contract_AddressIdRequest, Ru_Zveron_Contract_AddressResponse>
}

extension Ru_Zveron_Contract_AddressServiceClientProtocol {
  public var serviceName: String {
    return "ru.zveron.contract.AddressService"
  }

  ///*
  ///Мы проверяем уникальность адреса только по координатам, поэтому сначала проверим, что такой адрес существует,
  ///если да, то мы просто возвращаем его из БД(поэтому данные могут отличаться от того, что пришло в запросе), а не создаем.
  ///
  /// - Parameters:
  ///   - request: Request to send to SaveAddressIfNotExists.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func saveAddressIfNotExists(
    _ request: Ru_Zveron_Contract_AddressRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_Contract_AddressRequest, Ru_Zveron_Contract_AddressResponse> {
    return self.makeUnaryCall(
      path: Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.saveAddressIfNotExists.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSaveAddressIfNotExistsInterceptors() ?? []
    )
  }

  ///*
  ///Получить информацию адреса по идентификатору
  ///
  /// - Parameters:
  ///   - request: Request to send to GetAddress.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getAddress(
    _ request: Ru_Zveron_Contract_AddressIdRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_Contract_AddressIdRequest, Ru_Zveron_Contract_AddressResponse> {
    return self.makeUnaryCall(
      path: Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.getAddress.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAddressInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Ru_Zveron_Contract_AddressServiceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Ru_Zveron_Contract_AddressServiceNIOClient")
public final class Ru_Zveron_Contract_AddressServiceClient: Ru_Zveron_Contract_AddressServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the ru.zveron.contract.AddressService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Ru_Zveron_Contract_AddressServiceNIOClient: Ru_Zveron_Contract_AddressServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the ru.zveron.contract.AddressService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Ru_Zveron_Contract_AddressServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? { get }

  func makeSaveAddressIfNotExistsCall(
    _ request: Ru_Zveron_Contract_AddressRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_Contract_AddressRequest, Ru_Zveron_Contract_AddressResponse>

  func makeGetAddressCall(
    _ request: Ru_Zveron_Contract_AddressIdRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_Contract_AddressIdRequest, Ru_Zveron_Contract_AddressResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ru_Zveron_Contract_AddressServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Ru_Zveron_Contract_AddressServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSaveAddressIfNotExistsCall(
    _ request: Ru_Zveron_Contract_AddressRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_Contract_AddressRequest, Ru_Zveron_Contract_AddressResponse> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.saveAddressIfNotExists.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSaveAddressIfNotExistsInterceptors() ?? []
    )
  }

  public func makeGetAddressCall(
    _ request: Ru_Zveron_Contract_AddressIdRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_Contract_AddressIdRequest, Ru_Zveron_Contract_AddressResponse> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.getAddress.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAddressInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ru_Zveron_Contract_AddressServiceAsyncClientProtocol {
  public func saveAddressIfNotExists(
    _ request: Ru_Zveron_Contract_AddressRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ru_Zveron_Contract_AddressResponse {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.saveAddressIfNotExists.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSaveAddressIfNotExistsInterceptors() ?? []
    )
  }

  public func getAddress(
    _ request: Ru_Zveron_Contract_AddressIdRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ru_Zveron_Contract_AddressResponse {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.getAddress.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAddressInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Ru_Zveron_Contract_AddressServiceAsyncClient: Ru_Zveron_Contract_AddressServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Ru_Zveron_Contract_AddressServiceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'saveAddressIfNotExists'.
  func makeSaveAddressIfNotExistsInterceptors() -> [ClientInterceptor<Ru_Zveron_Contract_AddressRequest, Ru_Zveron_Contract_AddressResponse>]

  /// - Returns: Interceptors to use when invoking 'getAddress'.
  func makeGetAddressInterceptors() -> [ClientInterceptor<Ru_Zveron_Contract_AddressIdRequest, Ru_Zveron_Contract_AddressResponse>]
}

public enum Ru_Zveron_Contract_AddressServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AddressService",
    fullName: "ru.zveron.contract.AddressService",
    methods: [
      Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.saveAddressIfNotExists,
      Ru_Zveron_Contract_AddressServiceClientMetadata.Methods.getAddress,
    ]
  )

  public enum Methods {
    public static let saveAddressIfNotExists = GRPCMethodDescriptor(
      name: "SaveAddressIfNotExists",
      path: "/ru.zveron.contract.AddressService/SaveAddressIfNotExists",
      type: GRPCCallType.unary
    )

    public static let getAddress = GRPCMethodDescriptor(
      name: "GetAddress",
      path: "/ru.zveron.contract.AddressService/GetAddress",
      type: GRPCCallType.unary
    )
  }
}

