//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: apigateway.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `ApigatewayServiceClient`, then call methods of this protocol to make API calls.
public protocol ApigatewayServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? { get }

  func callApiGateway(
    _ request: ApiGatewayRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<ApiGatewayRequest, ApigatewayResponse>
}

extension ApigatewayServiceClientProtocol {
  public var serviceName: String {
    return "ru.zveron.contract.apigateway.ApigatewayService"
  }

  ///запрос из вне в шлюз
  ///
  /// - Parameters:
  ///   - request: Request to send to CallApiGateway.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func callApiGateway(
    _ request: ApiGatewayRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<ApiGatewayRequest, ApigatewayResponse> {
    return self.makeUnaryCall(
      path: ApigatewayServiceClientMetadata.Methods.callApiGateway.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCallApiGatewayInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension ApigatewayServiceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "ApigatewayServiceNIOClient")
public final class ApigatewayServiceClient: ApigatewayServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: ApigatewayServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the ru.zveron.contract.apigateway.ApigatewayService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct ApigatewayServiceNIOClient: ApigatewayServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: ApigatewayServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the ru.zveron.contract.apigateway.ApigatewayService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol ApigatewayServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? { get }

  func makeCallApiGatewayCall(
    _ request: ApiGatewayRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<ApiGatewayRequest, ApigatewayResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ApigatewayServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return ApigatewayServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeCallApiGatewayCall(
    _ request: ApiGatewayRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<ApiGatewayRequest, ApigatewayResponse> {
    return self.makeAsyncUnaryCall(
      path: ApigatewayServiceClientMetadata.Methods.callApiGateway.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCallApiGatewayInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ApigatewayServiceAsyncClientProtocol {
  public func callApiGateway(
    _ request: ApiGatewayRequest,
    callOptions: CallOptions? = nil
  ) async throws -> ApigatewayResponse {
    return try await self.performAsyncUnaryCall(
      path: ApigatewayServiceClientMetadata.Methods.callApiGateway.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCallApiGatewayInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct ApigatewayServiceAsyncClient: ApigatewayServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: ApigatewayServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ApigatewayServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol ApigatewayServiceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'callApiGateway'.
  func makeCallApiGatewayInterceptors() -> [ClientInterceptor<ApiGatewayRequest, ApigatewayResponse>]
}

public enum ApigatewayServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ApigatewayService",
    fullName: "ru.zveron.contract.apigateway.ApigatewayService",
    methods: [
      ApigatewayServiceClientMetadata.Methods.callApiGateway,
    ]
  )

  public enum Methods {
    public static let callApiGateway = GRPCMethodDescriptor(
      name: "CallApiGateway",
      path: "/ru.zveron.contract.apigateway.ApigatewayService/CallApiGateway",
      type: GRPCCallType.unary
    )
  }
}

