//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: lot_favorites.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Ru_Zveron_LotFavoritesServiceClient`, then call methods of this protocol to make API calls.
public protocol Ru_Zveron_LotFavoritesServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? { get }

  func addToFavorites(
    _ request: Ru_Zveron_AddLotToFavoritesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_AddLotToFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func removeFromFavorites(
    _ request: Ru_Zveron_RemoveLotFromFavoritesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_RemoveLotFromFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func existInFavorites(
    _ request: Ru_Zveron_LotsExistInFavoritesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_LotsExistInFavoritesRequest, Ru_Zveron_LotsExistInFavoritesResponse>

  func getFavoriteLots(
    _ request: Ru_Zveron_GetFavoriteLotsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_GetFavoriteLotsRequest, Ru_Zveron_GetFavoriteLotsResponse>

  func getCounter(
    _ request: Ru_Zveron_GetLotCounterRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_GetLotCounterRequest, Ru_Zveron_GetLotCounterResponse>

  func removeAllByOwner(
    _ request: Ru_Zveron_RemoveAllLotsByOwnerRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_RemoveAllLotsByOwnerRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func removeAllByFavoriteLot(
    _ request: Ru_Zveron_RemoveAllByFavoriteLotRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ru_Zveron_RemoveAllByFavoriteLotRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

extension Ru_Zveron_LotFavoritesServiceClientProtocol {
  public var serviceName: String {
    return "ru.zveron.LotFavoritesService"
  }

  /// Добавление объявления в избранное пользователя
  ///
  /// - Parameters:
  ///   - request: Request to send to addToFavorites.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func addToFavorites(
    _ request: Ru_Zveron_AddLotToFavoritesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_AddLotToFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.addToFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeaddToFavoritesInterceptors() ?? []
    )
  }

  /// Удаление объявления из избранного пользователя
  ///
  /// - Parameters:
  ///   - request: Request to send to removeFromFavorites.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func removeFromFavorites(
    _ request: Ru_Zveron_RemoveLotFromFavoritesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_RemoveLotFromFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeFromFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveFromFavoritesInterceptors() ?? []
    )
  }

  /// Проверка на существование объявлений в избранном пользователя
  ///
  /// - Parameters:
  ///   - request: Request to send to existInFavorites.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func existInFavorites(
    _ request: Ru_Zveron_LotsExistInFavoritesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_LotsExistInFavoritesRequest, Ru_Zveron_LotsExistInFavoritesResponse> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.existInFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeexistInFavoritesInterceptors() ?? []
    )
  }

  /// Получение списка избранных объявлений пользователя
  ///
  /// - Parameters:
  ///   - request: Request to send to getFavoriteLots.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getFavoriteLots(
    _ request: Ru_Zveron_GetFavoriteLotsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_GetFavoriteLotsRequest, Ru_Zveron_GetFavoriteLotsResponse> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getFavoriteLots.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetFavoriteLotsInterceptors() ?? []
    )
  }

  /// Получение количества добавлений объявления в избранное
  ///
  /// - Parameters:
  ///   - request: Request to send to getCounter.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getCounter(
    _ request: Ru_Zveron_GetLotCounterRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_GetLotCounterRequest, Ru_Zveron_GetLotCounterResponse> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getCounter.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetCounterInterceptors() ?? []
    )
  }

  /// Удаление всех записей из избранного определенного пользователя
  ///
  /// - Parameters:
  ///   - request: Request to send to removeAllByOwner.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func removeAllByOwner(
    _ request: Ru_Zveron_RemoveAllLotsByOwnerRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_RemoveAllLotsByOwnerRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByOwner.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveAllByOwnerInterceptors() ?? []
    )
  }

  /// Удаление опредленного объявления из всех список избранного
  ///
  /// - Parameters:
  ///   - request: Request to send to removeAllByFavoriteLot.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func removeAllByFavoriteLot(
    _ request: Ru_Zveron_RemoveAllByFavoriteLotRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ru_Zveron_RemoveAllByFavoriteLotRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByFavoriteLot.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveAllByFavoriteLotInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Ru_Zveron_LotFavoritesServiceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Ru_Zveron_LotFavoritesServiceNIOClient")
public final class Ru_Zveron_LotFavoritesServiceClient: Ru_Zveron_LotFavoritesServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the ru.zveron.LotFavoritesService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Ru_Zveron_LotFavoritesServiceNIOClient: Ru_Zveron_LotFavoritesServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the ru.zveron.LotFavoritesService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Ru_Zveron_LotFavoritesServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? { get }

  func makeAddToFavoritesCall(
    _ request: Ru_Zveron_AddLotToFavoritesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_AddLotToFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeRemoveFromFavoritesCall(
    _ request: Ru_Zveron_RemoveLotFromFavoritesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_RemoveLotFromFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeExistInFavoritesCall(
    _ request: Ru_Zveron_LotsExistInFavoritesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_LotsExistInFavoritesRequest, Ru_Zveron_LotsExistInFavoritesResponse>

  func makeGetFavoriteLotsCall(
    _ request: Ru_Zveron_GetFavoriteLotsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_GetFavoriteLotsRequest, Ru_Zveron_GetFavoriteLotsResponse>

  func makeGetCounterCall(
    _ request: Ru_Zveron_GetLotCounterRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_GetLotCounterRequest, Ru_Zveron_GetLotCounterResponse>

  func makeRemoveAllByOwnerCall(
    _ request: Ru_Zveron_RemoveAllLotsByOwnerRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_RemoveAllLotsByOwnerRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeRemoveAllByFavoriteLotCall(
    _ request: Ru_Zveron_RemoveAllByFavoriteLotRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_RemoveAllByFavoriteLotRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ru_Zveron_LotFavoritesServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Ru_Zveron_LotFavoritesServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeAddToFavoritesCall(
    _ request: Ru_Zveron_AddLotToFavoritesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_AddLotToFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.addToFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeaddToFavoritesInterceptors() ?? []
    )
  }

  public func makeRemoveFromFavoritesCall(
    _ request: Ru_Zveron_RemoveLotFromFavoritesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_RemoveLotFromFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeFromFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveFromFavoritesInterceptors() ?? []
    )
  }

  public func makeExistInFavoritesCall(
    _ request: Ru_Zveron_LotsExistInFavoritesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_LotsExistInFavoritesRequest, Ru_Zveron_LotsExistInFavoritesResponse> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.existInFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeexistInFavoritesInterceptors() ?? []
    )
  }

  public func makeGetFavoriteLotsCall(
    _ request: Ru_Zveron_GetFavoriteLotsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_GetFavoriteLotsRequest, Ru_Zveron_GetFavoriteLotsResponse> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getFavoriteLots.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetFavoriteLotsInterceptors() ?? []
    )
  }

  public func makeGetCounterCall(
    _ request: Ru_Zveron_GetLotCounterRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_GetLotCounterRequest, Ru_Zveron_GetLotCounterResponse> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getCounter.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetCounterInterceptors() ?? []
    )
  }

  public func makeRemoveAllByOwnerCall(
    _ request: Ru_Zveron_RemoveAllLotsByOwnerRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_RemoveAllLotsByOwnerRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByOwner.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveAllByOwnerInterceptors() ?? []
    )
  }

  public func makeRemoveAllByFavoriteLotCall(
    _ request: Ru_Zveron_RemoveAllByFavoriteLotRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ru_Zveron_RemoveAllByFavoriteLotRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByFavoriteLot.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveAllByFavoriteLotInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ru_Zveron_LotFavoritesServiceAsyncClientProtocol {
  public func addToFavorites(
    _ request: Ru_Zveron_AddLotToFavoritesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.addToFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeaddToFavoritesInterceptors() ?? []
    )
  }

  public func removeFromFavorites(
    _ request: Ru_Zveron_RemoveLotFromFavoritesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeFromFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveFromFavoritesInterceptors() ?? []
    )
  }

  public func existInFavorites(
    _ request: Ru_Zveron_LotsExistInFavoritesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ru_Zveron_LotsExistInFavoritesResponse {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.existInFavorites.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeexistInFavoritesInterceptors() ?? []
    )
  }

  public func getFavoriteLots(
    _ request: Ru_Zveron_GetFavoriteLotsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ru_Zveron_GetFavoriteLotsResponse {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getFavoriteLots.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetFavoriteLotsInterceptors() ?? []
    )
  }

  public func getCounter(
    _ request: Ru_Zveron_GetLotCounterRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ru_Zveron_GetLotCounterResponse {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getCounter.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetCounterInterceptors() ?? []
    )
  }

  public func removeAllByOwner(
    _ request: Ru_Zveron_RemoveAllLotsByOwnerRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByOwner.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveAllByOwnerInterceptors() ?? []
    )
  }

  public func removeAllByFavoriteLot(
    _ request: Ru_Zveron_RemoveAllByFavoriteLotRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByFavoriteLot.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeremoveAllByFavoriteLotInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Ru_Zveron_LotFavoritesServiceAsyncClient: Ru_Zveron_LotFavoritesServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Ru_Zveron_LotFavoritesServiceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'addToFavorites'.
  func makeaddToFavoritesInterceptors() -> [ClientInterceptor<Ru_Zveron_AddLotToFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'removeFromFavorites'.
  func makeremoveFromFavoritesInterceptors() -> [ClientInterceptor<Ru_Zveron_RemoveLotFromFavoritesRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'existInFavorites'.
  func makeexistInFavoritesInterceptors() -> [ClientInterceptor<Ru_Zveron_LotsExistInFavoritesRequest, Ru_Zveron_LotsExistInFavoritesResponse>]

  /// - Returns: Interceptors to use when invoking 'getFavoriteLots'.
  func makegetFavoriteLotsInterceptors() -> [ClientInterceptor<Ru_Zveron_GetFavoriteLotsRequest, Ru_Zveron_GetFavoriteLotsResponse>]

  /// - Returns: Interceptors to use when invoking 'getCounter'.
  func makegetCounterInterceptors() -> [ClientInterceptor<Ru_Zveron_GetLotCounterRequest, Ru_Zveron_GetLotCounterResponse>]

  /// - Returns: Interceptors to use when invoking 'removeAllByOwner'.
  func makeremoveAllByOwnerInterceptors() -> [ClientInterceptor<Ru_Zveron_RemoveAllLotsByOwnerRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'removeAllByFavoriteLot'.
  func makeremoveAllByFavoriteLotInterceptors() -> [ClientInterceptor<Ru_Zveron_RemoveAllByFavoriteLotRequest, SwiftProtobuf.Google_Protobuf_Empty>]
}

public enum Ru_Zveron_LotFavoritesServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "LotFavoritesService",
    fullName: "ru.zveron.LotFavoritesService",
    methods: [
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.addToFavorites,
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeFromFavorites,
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.existInFavorites,
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getFavoriteLots,
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.getCounter,
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByOwner,
      Ru_Zveron_LotFavoritesServiceClientMetadata.Methods.removeAllByFavoriteLot,
    ]
  )

  public enum Methods {
    public static let addToFavorites = GRPCMethodDescriptor(
      name: "addToFavorites",
      path: "/ru.zveron.LotFavoritesService/addToFavorites",
      type: GRPCCallType.unary
    )

    public static let removeFromFavorites = GRPCMethodDescriptor(
      name: "removeFromFavorites",
      path: "/ru.zveron.LotFavoritesService/removeFromFavorites",
      type: GRPCCallType.unary
    )

    public static let existInFavorites = GRPCMethodDescriptor(
      name: "existInFavorites",
      path: "/ru.zveron.LotFavoritesService/existInFavorites",
      type: GRPCCallType.unary
    )

    public static let getFavoriteLots = GRPCMethodDescriptor(
      name: "getFavoriteLots",
      path: "/ru.zveron.LotFavoritesService/getFavoriteLots",
      type: GRPCCallType.unary
    )

    public static let getCounter = GRPCMethodDescriptor(
      name: "getCounter",
      path: "/ru.zveron.LotFavoritesService/getCounter",
      type: GRPCCallType.unary
    )

    public static let removeAllByOwner = GRPCMethodDescriptor(
      name: "removeAllByOwner",
      path: "/ru.zveron.LotFavoritesService/removeAllByOwner",
      type: GRPCCallType.unary
    )

    public static let removeAllByFavoriteLot = GRPCMethodDescriptor(
      name: "removeAllByFavoriteLot",
      path: "/ru.zveron.LotFavoritesService/removeAllByFavoriteLot",
      type: GRPCCallType.unary
    )
  }
}

